apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: default
type: Opaque
stringData:
  NAME: todolist
  USER: myuser
  PASSWORD: mypassword
  HOST: mysql-0.mysql.mysql.svc.cluster.local